name: Build and test

on:
  push:
    branches: [ release, github-actions ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2016
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      TORSHARP_TEST_CACHE: ${{ github.workspace }}/Knapcode.TorSharp.Tests/cache
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: ${{ matrix.os }}-nuget
        restore-keys: |
          ${{ matrix.os }}-nuget
    - name: Cache test downloads
      uses: actions/cache@v2
      with:
        path: ${{ env.TORSHARP_TEST_CACHE }}
        key: ${{ matrix.os }}-torsharp-test
        restore-keys: |
          ${{ matrix.os }}-torsharp-test
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore
      run: dotnet restore
      if: runner.os == 'Linux'
    - name: Build
      run: dotnet build --configuration Release --no-restore
      if: runner.os == 'Linux'
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      if: runner.os == 'Linux'
    - name: Build
      run: .\build.ps1
      if: runner.os == 'Windows'
    - name: Test
      run: .\test.ps1
      if: runner.os == 'Windows'
